### ISSUE TITLE
Check changes in recent projects

### ISSUE THREAD

**Issue by epernia** [martinribelotta/embedded-ide#10]

**Comment by martinribelotta** [comment]
Explicalo un poco mas... no me queda claro el objetivo de esto

**Comment by epernia** [comment]
La idea sería que al modificar la carpeta de proyectos ya sea cambiando la ruta donde está (en configuración), o borrando, o agregando un nuevo proyecto por afuera el IDE este chequee y modifique la lista de proyectos cada vez que se toca el menú de proyectos. Esto si lo hace en el file browser de archivos y carpetas cuando abris un proyecto.

**Comment by denisacostaq** [comment]
Con [QFileSystemWatcher](http://doc.qt.io/qt-4.8/qfilesystemwatcher.html) resuelves buena parte, 
te suscribes a estos tios:
[directoryChanged](http://doc.qt.io/qt-4.8/qfilesystemwatcher.html#directoryChanged)
[fileChangedhttp://doc.qt.io/qt-4.8/qfilesystemwatcher.html#fileChanged)
y le preguntas al usuario con un message box si quiere, recargar del archivo o sobrescribir del buffer

**Comment by martinribelotta** [comment]
@denisacostaq aparte hay que checkear al arranque al menos. Es una operación molesta pero se hace:
```c++
foreach(QString d, QDir(projectPath()).entryList(QDir::Dirs | QDir::NoDotAndDotDot)) {
  if (QFileInfo(QDir(d).fileName("Makefile")).exist()) {
    // Add to list
  }
}
```
Esto podría ser parte de la función [lastProjectsList](https://github.com/martinribelotta/embedded-ide/blob/master/mainwindow.cpp#L49) teniendo en cuenta de no repetir proyectos.

Así, se podría regenerar la lista con QFileSystemWatcher tal cual decís vos
