### ISSUE TITLE
Sometimes, files are opened to me in gedit

### ISSUE THREAD

**Issue by MatiasLoiseau** [martinribelotta/embedded-ide#16]
When somebody gives me an external project, paste the project in my workspace. I open the embedded ide, and click in "open project", i select the makefile and all is fine, but when i click in some file, to edit the text, it is opened in gedit.
It is only when i open externals projects
Any solution ?

Cuando alguien me da un proyecto externo, pego la carpeta en mi workspace, luego abro el IDE, selecciono abrir proyecto, busco el makefile y lo carga perfecto. Pero el problema es que cuando quiero editar el texto, le doy click a cualquier archivo, y me lo abre con el gedit, no en el mismo IDE.
Esto pasa solo cuando abro proyectos que yo no creo.
Hay alguna manera de que me los abra desde el IDE? O sino alguna solución que no sea desde el ide mismo, ya que no soy tan buen usuario de linux.

Desde ya gracias y saludos  ! !

**Comment by martinribelotta** [comment]
Que tipos de archivos no se abren con el IDE?
El abrir con el sistema fue eliminado desde 3b2d978f6d0d7694b9a135fda26052d8e63b38bd
Si me decis como reproducir el problema lo veo pero si no, lo cierro por obsoleto.

**Comment by MatiasLoiseau** [comment]
Perdon si mi problema no debe venir aca, es que no sabía bien a quien preguntarle. Te paso la imagen aunque creo que ya entendiste el problema
https://ibb.co/gYNjHa
Si masomenos sabes como puedo solucionar que me aparezca el codigo en el embedded y no en gedit estaría joya pero si crees que el problema es que tengo configurado algo mal desde el linux trato de solucionarlo por otro lado y cerra el problema, no hay drama.
Perdon por la molestia

**Comment by martinribelotta** [comment]
Te recomiendo que lo postees en la lista ciaa ide o ciaa firmware.
O sino completame la informacion que te pudo por aca:
 - version de tu IDE
 - version y configuracion de tu sistema operativo
 - una receta para reproducir el error
Al menos se me ocurren dos cosas, probar si se reproduce en otra maquina y chequear que sea la ultima version y si no lo es bajarse la ultima y probar.
Por ahora cierro el bug por el simple hecho que ya no hay mas codigo que haga lo que a vos te pasa en la version actual de embedded ide. Con lo que, por lo menos, dedusco que tenes una version vieja.
