### ISSUE TITLE
libstdc++.so.6 version requirement

### ISSUE THREAD

**Issue by probonopd** [martinribelotta/embedded-ide#19]
Would it be possible to lower the required libstdc++.so.6 version so that it runs on Ubuntu trusty?

```
embedded-ide: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7989/bin/embedded-ide)

Parent pid 7989, child pid 7992
```

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266109525#L556

**Comment by martinribelotta** [comment]
Fixed manually for v0.5.0
