### ISSUE TITLE
No esta el .Appimage para descargar en Linux del release 0.5.0

### ISSUE THREAD

**Issue by MatiasLoiseau** [martinribelotta/embedded-ide#20]
Hola Martín, no esta mas el link para descargar el Appimage del último release, lo sacaste por algún motivo ?

Saludos ! !

**Comment by martinribelotta** [comment]
Nunca lo genere... cuando tenga tiempo lo genero y lo subo

**Comment by MatiasLoiseau** [comment]
Perdón Martín, lo había descargado de tu publicación en embebidos32 y era de este repositorio:
https://github.com/martinribelotta/embedded-ide-builder/releases/tag/v0.5.0

Cuál es la diferencia entre embedded-ide-builder y embedded-ide ? 

Disculpa que moleste con algunas preguntas es que lo quiero implementar en una materia de la facu y quería saber bien la fuente.

Saludos !!

**Comment by martinribelotta** [comment]
El repo embedded-ide contiene solo el IDE, mientras que embedded-ide-builder es un repo para construir las imagenes con el toolchain, las herramientas de linea de comandos y openocd.

**Comment by MatiasLoiseau** [comment]
Bueno gracias por la data. Cerra el issue si queres.
Saludos !

**Comment by martinribelotta** [comment]
Fixed
