### ISSUE TITLE
Bug en herramienta "Buscar simbolo bajo el cursor"

### ISSUE THREAD

**Issue by arielberardi** [martinribelotta/embedded-ide#21]
Buen día Martín te comento el siguiente bug (según mi criterio) que he encontrado. 

La herramienta en general funciona muy bien, ahora bien si yo por algún motivo busco dos veces la misma función y selecciono dos veces el archivo donde se encuentra definida o declarada la misma, el archivo en el IDE se abre las dos veces sin importar si ya está abierto o no.  Esto pasa de forma indefinida como se ve en la imagen 

![image](https://user-images.githubusercontent.com/20867835/34964799-0b252548-fa2e-11e7-9e89-e213a3007a2c.png)

Estoy atento a cualquier duda que genere mi explicación. Saludos
Ariel

**Comment by martinribelotta** [comment]
Es un bug conocido de la version 0.5
En la proxima 0.6 a salir en unos dias esto esta corregido.

**Comment by martinribelotta** [comment]
Closed due bug not exist anymore in current master
