### ISSUE TITLE
Add TODO indexer - Feature

### ISSUE THREAD

**Issue by fransuar** [martinribelotta/embedded-ide#34]
Hola compañero desarrollador. Esto no lo he visto en ningún otro editor, lo cual no quita que exista, pero me pareció interesante.
Que tal hacer un indexador TODO, algo que sea un poquito mas complejo que usar el buscador con la palabra clave TODO. O sea, un listadito de cosas por hacer, en donde este la palabra clave TODO, junto con una pequeña descripción.
Saludos

**Comment by martinribelotta** [comment]
Suena bien... tanto en eclipse, netbeans, vscode y qtcreator eso es algo muy util. Lo pongo en lista de TODO

**Comment by martinribelotta** [comment]
A partir del commit 75e98a67622591785f094b713e1ef0aa865ba330 se exportan las variables de entorno `CURRENT_PROJECT_DIR` y `CURRENT_PROJECT_FILE` . Con ello se puede añadir al tool manager el siguiente comando:

| command name | command |
|-----------------------|---------------|
|Show todo | `sh -c "grep -nRE '\bTODO\b'"` |

Que posibilita buscar y mostrar todos los TODO del proyecto. Esto aunado al nuevo sistema de indexado de errores y marcas de código de la consola permite saltar con un solo click a la linea correspondiente:

![image](https://user-images.githubusercontent.com/692175/55689045-6fd80b80-5956-11e9-9969-2225a7cbb06f.png)
