### ISSUE TITLE
Qt ejecutable embebido

### ISSUE THREAD

**Issue by rsc9421** [martinribelotta/embedded-ide#37]
Hola martin, soy el que estaba haciendo el IDE para GHDL, me gustaria terminarlo y para eso te queria hacer una consulta (sorry si te escribo por aca no queria desvirtuar embebidos32) 
Vi que en la ultima version de embedded ide compilaste TODO en un solo ejecutable(el programa de Qt + gcc+arm+none-eabi + etc) y yo queria hacer lo mismo ( IDE + ghdl + gtkwave en un mismo .appimage o .exe) como hiciste? 
intente añadir el ejecutable al resource file (.qrc) y abrirlo con qprocess pero demora tanto que se me tilda la compu durante la compilacion capas estoy haciendo algo mal...

**Comment by martinribelotta** [comment]
Uso el sistema de appimage. Especificamente el proyecto linuxdeployqt
